In [1]:
import akshare as ak
symbol = '600000'
# symbol = '600734'
start_date = '20240813'
end_date = '20500101'
stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=symbol, start_date=start_date, end_date=end_date,
                                                period="daily", adjust="")
stock_zh_a_hist_df

,日期,股票代码,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,2024-08-13,600000,8.56,8.59,8.67,8.54,272116,234443969.0,1.52,0.12,0.01,0.09
1,2024-08-14,600000,8.63,8.57,8.65,8.54,211457,181445555.0,1.28,-0.23,-0.02,0.07
2,2024-08-15,600000,8.51,8.74,8.75,8.51,450662,392033450.0,2.80,1.98,0.17,0.15
3,2024-08-16,600000,8.74,8.85,8.86,8.70,375669,331065667.0,1.83,1.26,0.11,0.13
4,2024-08-19,600000,8.86,9.02,9.03,8.84,589380,528390434.0,2.15,1.92,0.17,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...
127,2025-02-26,600000,10.15,10.18,10.32,10.12,555367,567601088.0,1.98,0.79,0.08,0.19
128,2025-02-27,600000,10.22,10.24,10.26,10.11,379992,387232885.0,1.47,0.59,0.06,0.13
129,2025-02-28,600000,10.23,10.17,10.30,10.17,446511,457102788.0,1.27,-0.68,-0.07,0.15
130,2025-03-03,600000,10.19,10.15,10.22,10.08,430109,436849850.0,1.38,-0.20,-0.02,0.15
131,2025-03-04,600000,10.10,10.10,10.19,10.10,297698,301634439.0,0.89,-0.49,-0.05,0.10

In [3]:
ak.stock_zh_a_spot_em()

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,301557,N常友,89.99,211.60,61.11,92696,8.852068e+08,172.33,130.00,...,NaN,83.66,37.89,4.00,3987265311,997089200,-0.01,-0.01,211.60,211.60
1,2,603409,N汇通,50.81,110.13,26.63,232895,1.266359e+09,132.71,77.77,...,NaN,75.43,38.13,4.44,6403584300,1568804327,0.00,-0.39,110.13,110.13
2,3,832149,利尔达,17.29,30.00,3.99,433147,6.790698e+08,32.18,17.29,...,2.76,37.53,-49.74,10.49,7289982700,1995451453,0.00,0.00,37.44,94.93
3,4,837006,晟楠科技,31.39,29.98,7.24,162694,4.840618e+08,29.61,31.39,...,4.16,47.44,-195.48,8.85,2834115208,1076421988,0.00,0.00,7.02,27.60
4,5,831167,鑫汇科,33.87,29.97,7.81,45497,1.481186e+08,15.23,33.87,...,2.54,15.82,59.27,6.26,1692922212,974055577,0.00,0.00,5.91,69.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,300671,富满微,37.39,7.10,2.48,134826,4.935690e+08,11.69,38.48,...,1.45,6.21,-94.21,4.62,8140718045,8112628060,0.03,0.08,-2.50,5.21
196,197,300661,圣邦股份,98.76,7.08,6.53,169789,1.658722e+09,10.97,101.00,...,1.62,3.75,122.71,10.86,46612805537,44692370328,0.07,0.05,12.55,20.76
197,198,002031,巨轮智能,10.60,7.07,0.70,5580062,5.793310e+09,13.03,10.79,...,0.97,28.15,2993.00,9.59,23313594102,21011828938,0.00,0.09,126.50,113.28
198,199,301596,瑞迪智驱,143.17,7.06,9.44,26232,3.683744e+08,10.07,145.66,...,0.88,19.04,80.63,9.82,7891254368,1972813592,0.02,0.08,35.05,43.17
199,200,831396,许昌智能,13.81,7.05,0.91,184675,2.474090e+08,8.91,13.81,...,1.28,19.62,39.80,3.97,2286590750,1300202744,0.44,0.36,16.05,46.91

In [7]:
import akshare as ak

stock_zh_a_hist_tx_df = ak.stock_zh_a_hist_tx(symbol="sh600000", start_date=start_date, end_date=end_date, adjust="")
stock_zh_a_hist_tx_df

  0%|          | 0/2 [00:00<?, ?it/s]

           date   open  close   high    low    amount
0    2024-08-13   8.56   8.59   8.67   8.54  272116.0
1    2024-08-14   8.63   8.57   8.65   8.54  211457.0
2    2024-08-15   8.51   8.74   8.75   8.51  450662.0
3    2024-08-16   8.74   8.85   8.86   8.70  375669.0
4    2024-08-19   8.86   9.02   9.03   8.84  589380.0
..          ...    ...    ...    ...    ...       ...
127  2025-02-26  10.15  10.18  10.32  10.12  555367.0
128  2025-02-27  10.22  10.24  10.26  10.11  379992.0
129  2025-02-28  10.23  10.17  10.30  10.17  446511.0
130  2025-03-03  10.19  10.15  10.22  10.08  430109.0
131  2025-03-04  10.10  10.10  10.19  10.10  297698.0

[132 rows x 6 columns]